version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 15          
    
    groups:
      production-dependencies:
        patterns:
          - "*"
        dependency-type: "production"
      
      development-dependencies:
        patterns:
          - "*"
        dependency-type: "development"
     
      nextjs:
        patterns:
          - "next"
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
        dependency-type: "production"

    ignore:
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]

    versioning-strategy: "increase-if-necessary"  
    rebase-strategy: "auto"
